// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/protos/service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBRequest) Reset() {
	*x = PingDBRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBRequest) ProtoMessage() {}

func (x *PingDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBRequest.ProtoReflect.Descriptor instead.
func (*PingDBRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{0}
}

type PingDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBResponse) Reset() {
	*x = PingDBResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBResponse) ProtoMessage() {}

func (x *PingDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBResponse.ProtoReflect.Descriptor instead.
func (*PingDBResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{1}
}

// /////////////////////////////////
type CreateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShortURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShortURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// /////////////////////////////////
type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{4}
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{5}
}

func (x *StatResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

// /////////////////////////////////
type ShortUrl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code is the shortened code associated with the URL.
	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	// URL is the original URL that has been shortened.
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortUrl) Reset() {
	*x = ShortUrl{}
	mi := &file_internal_protos_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrl) ProtoMessage() {}

func (x *ShortUrl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrl.ProtoReflect.Descriptor instead.
func (*ShortUrl) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{6}
}

func (x *ShortUrl) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortUrl) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlsRequest) Reset() {
	*x = GetUrlsRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlsRequest) ProtoMessage() {}

func (x *GetUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlsRequest.ProtoReflect.Descriptor instead.
func (*GetUrlsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{7}
}

type GetUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*ShortUrl            `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlsResponse) Reset() {
	*x = GetUrlsResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlsResponse) ProtoMessage() {}

func (x *GetUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlsResponse.ProtoReflect.Descriptor instead.
func (*GetUrlsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetUrlsResponse) GetUrls() []*ShortUrl {
	if x != nil {
		return x.Urls
	}
	return nil
}

// ///////////////////////////////// "/{id}", c.GetLongURLHandler() - get the original URL  by the alias
type GetUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlRequest) Reset() {
	*x = GetUrlRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlRequest) ProtoMessage() {}

func (x *GetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUrlRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUrlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlResponse) Reset() {
	*x = GetUrlResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlResponse) ProtoMessage() {}

func (x *GetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUrlResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// /////////////////////////////////
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // ids - aliases to delete for a specific user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{12}
}

// //////////////////////////////////
type BatchFullUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchFullUrl) Reset() {
	*x = BatchFullUrl{}
	mi := &file_internal_protos_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFullUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFullUrl) ProtoMessage() {}

func (x *BatchFullUrl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFullUrl.ProtoReflect.Descriptor instead.
func (*BatchFullUrl) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{13}
}

func (x *BatchFullUrl) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchFullUrl) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchShortUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortUrl) Reset() {
	*x = BatchShortUrl{}
	mi := &file_internal_protos_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortUrl) ProtoMessage() {}

func (x *BatchShortUrl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortUrl.ProtoReflect.Descriptor instead.
func (*BatchShortUrl) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{14}
}

func (x *BatchShortUrl) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchShortUrl) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchFullUrl        `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{15}
}

func (x *BatchRequest) GetUrls() []*BatchFullUrl {
	if x != nil {
		return x.Urls
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*BatchShortUrl       `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{16}
}

func (x *BatchResponse) GetResult() []*BatchShortUrl {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_protos_service_proto protoreflect.FileDescriptor

const file_internal_protos_service_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/protos/service.proto\x12\aservice\"\x0f\n" +
	"\rPingDBRequest\"\x10\n" +
	"\x0ePingDBResponse\")\n" +
	"\x15CreateShortURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"0\n" +
	"\x16CreateShortURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\r\n" +
	"\vStatRequest\"8\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users\"J\n" +
	"\bShortUrl\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"\x10\n" +
	"\x0eGetUrlsRequest\"8\n" +
	"\x0fGetUrlsResponse\x12%\n" +
	"\x04urls\x18\x01 \x03(\v2\x11.service.ShortUrlR\x04urls\"\x1f\n" +
	"\rGetUrlRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x0eGetUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x10\n" +
	"\x0eDeleteResponse\"X\n" +
	"\fBatchFullUrl\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"S\n" +
	"\rBatchShortUrl\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"9\n" +
	"\fBatchRequest\x12)\n" +
	"\x04urls\x18\x01 \x03(\v2\x15.service.BatchFullUrlR\x04urls\"?\n" +
	"\rBatchResponse\x12.\n" +
	"\x06result\x18\x01 \x03(\v2\x16.service.BatchShortUrlR\x06result2\xc3\x03\n" +
	"\tShortener\x129\n" +
	"\x06PingDB\x12\x16.service.PingDBRequest\x1a\x17.service.PingDBResponse\x12Q\n" +
	"\x0eCreateShortURL\x12\x1e.service.CreateShortURLRequest\x1a\x1f.service.CreateShortURLResponse\x126\n" +
	"\x05Batch\x12\x15.service.BatchRequest\x1a\x16.service.BatchResponse\x129\n" +
	"\x06Delete\x12\x16.service.DeleteRequest\x1a\x17.service.DeleteResponse\x129\n" +
	"\x06GetURL\x12\x16.service.GetUrlRequest\x1a\x17.service.GetUrlResponse\x12<\n" +
	"\aGetURLs\x12\x17.service.GetUrlsRequest\x1a\x18.service.GetUrlsResponse\x12<\n" +
	"\rInternalStats\x12\x14.service.StatRequest\x1a\x15.service.StatResponseB=Z;github.com/Painkiller675/url_shortener_6750/internal/protosb\x06proto3"

var (
	file_internal_protos_service_proto_rawDescOnce sync.Once
	file_internal_protos_service_proto_rawDescData []byte
)

func file_internal_protos_service_proto_rawDescGZIP() []byte {
	file_internal_protos_service_proto_rawDescOnce.Do(func() {
		file_internal_protos_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protos_service_proto_rawDesc), len(file_internal_protos_service_proto_rawDesc)))
	})
	return file_internal_protos_service_proto_rawDescData
}

var file_internal_protos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_protos_service_proto_goTypes = []any{
	(*PingDBRequest)(nil),          // 0: service.PingDBRequest
	(*PingDBResponse)(nil),         // 1: service.PingDBResponse
	(*CreateShortURLRequest)(nil),  // 2: service.CreateShortURLRequest
	(*CreateShortURLResponse)(nil), // 3: service.CreateShortURLResponse
	(*StatRequest)(nil),            // 4: service.StatRequest
	(*StatResponse)(nil),           // 5: service.StatResponse
	(*ShortUrl)(nil),               // 6: service.ShortUrl
	(*GetUrlsRequest)(nil),         // 7: service.GetUrlsRequest
	(*GetUrlsResponse)(nil),        // 8: service.GetUrlsResponse
	(*GetUrlRequest)(nil),          // 9: service.GetUrlRequest
	(*GetUrlResponse)(nil),         // 10: service.GetUrlResponse
	(*DeleteRequest)(nil),          // 11: service.DeleteRequest
	(*DeleteResponse)(nil),         // 12: service.DeleteResponse
	(*BatchFullUrl)(nil),           // 13: service.BatchFullUrl
	(*BatchShortUrl)(nil),          // 14: service.BatchShortUrl
	(*BatchRequest)(nil),           // 15: service.BatchRequest
	(*BatchResponse)(nil),          // 16: service.BatchResponse
}
var file_internal_protos_service_proto_depIdxs = []int32{
	6,  // 0: service.GetUrlsResponse.urls:type_name -> service.ShortUrl
	13, // 1: service.BatchRequest.urls:type_name -> service.BatchFullUrl
	14, // 2: service.BatchResponse.result:type_name -> service.BatchShortUrl
	0,  // 3: service.Shortener.PingDB:input_type -> service.PingDBRequest
	2,  // 4: service.Shortener.CreateShortURL:input_type -> service.CreateShortURLRequest
	15, // 5: service.Shortener.Batch:input_type -> service.BatchRequest
	11, // 6: service.Shortener.Delete:input_type -> service.DeleteRequest
	9,  // 7: service.Shortener.GetURL:input_type -> service.GetUrlRequest
	7,  // 8: service.Shortener.GetURLs:input_type -> service.GetUrlsRequest
	4,  // 9: service.Shortener.InternalStats:input_type -> service.StatRequest
	1,  // 10: service.Shortener.PingDB:output_type -> service.PingDBResponse
	3,  // 11: service.Shortener.CreateShortURL:output_type -> service.CreateShortURLResponse
	16, // 12: service.Shortener.Batch:output_type -> service.BatchResponse
	12, // 13: service.Shortener.Delete:output_type -> service.DeleteResponse
	10, // 14: service.Shortener.GetURL:output_type -> service.GetUrlResponse
	8,  // 15: service.Shortener.GetURLs:output_type -> service.GetUrlsResponse
	5,  // 16: service.Shortener.InternalStats:output_type -> service.StatResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_protos_service_proto_init() }
func file_internal_protos_service_proto_init() {
	if File_internal_protos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protos_service_proto_rawDesc), len(file_internal_protos_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_service_proto_goTypes,
		DependencyIndexes: file_internal_protos_service_proto_depIdxs,
		MessageInfos:      file_internal_protos_service_proto_msgTypes,
	}.Build()
	File_internal_protos_service_proto = out.File
	file_internal_protos_service_proto_goTypes = nil
	file_internal_protos_service_proto_depIdxs = nil
}
