// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/protos/service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBRequest) Reset() {
	*x = PingDBRequest{}
	mi := &file_internal_protos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBRequest) ProtoMessage() {}

func (x *PingDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBRequest.ProtoReflect.Descriptor instead.
func (*PingDBRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{0}
}

type PingDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBResponse) Reset() {
	*x = PingDBResponse{}
	mi := &file_internal_protos_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBResponse) ProtoMessage() {}

func (x *PingDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBResponse.ProtoReflect.Descriptor instead.
func (*PingDBResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_service_proto_rawDescGZIP(), []int{1}
}

var File_internal_protos_service_proto protoreflect.FileDescriptor

const file_internal_protos_service_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/protos/service.proto\x12\aservice\"\x0f\n" +
	"\rPingDBRequest\"\x10\n" +
	"\x0ePingDBResponse2H\n" +
	"\tShortener\x12;\n" +
	"\x06PingDB\x12\x16.service.PingDBRequest\x1a\x17.service.PingDBResponse\"\x00B=Z;github.com/Painkiller675/url_shortener_6750/internal/protosb\x06proto3"

var (
	file_internal_protos_service_proto_rawDescOnce sync.Once
	file_internal_protos_service_proto_rawDescData []byte
)

func file_internal_protos_service_proto_rawDescGZIP() []byte {
	file_internal_protos_service_proto_rawDescOnce.Do(func() {
		file_internal_protos_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protos_service_proto_rawDesc), len(file_internal_protos_service_proto_rawDesc)))
	})
	return file_internal_protos_service_proto_rawDescData
}

var file_internal_protos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protos_service_proto_goTypes = []any{
	(*PingDBRequest)(nil),  // 0: service.PingDBRequest
	(*PingDBResponse)(nil), // 1: service.PingDBResponse
}
var file_internal_protos_service_proto_depIdxs = []int32{
	0, // 0: service.Shortener.PingDB:input_type -> service.PingDBRequest
	1, // 1: service.Shortener.PingDB:output_type -> service.PingDBResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protos_service_proto_init() }
func file_internal_protos_service_proto_init() {
	if File_internal_protos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protos_service_proto_rawDesc), len(file_internal_protos_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_service_proto_goTypes,
		DependencyIndexes: file_internal_protos_service_proto_depIdxs,
		MessageInfos:      file_internal_protos_service_proto_msgTypes,
	}.Build()
	File_internal_protos_service_proto = out.File
	file_internal_protos_service_proto_goTypes = nil
	file_internal_protos_service_proto_depIdxs = nil
}
