
syntax = "proto3";

package service;

option go_package = "github.com/Painkiller675/url_shortener_6750/internal/protos";


message PingDBRequest {}

message PingDBResponse {}
///////////////////////////////////
message CreateShortURLRequest{
  string url = 1;
}

message CreateShortURLResponse{
  string result = 1;
}
///////////////////////////////////
message StatRequest {
}

message StatResponse {
  int32 urls = 1;
  int32 users = 2;
}
///////////////////////////////////
message ShortUrl {
  // Code is the shortened code associated with the URL.
  string short_url = 1;

  // URL is the original URL that has been shortened.
  string original_url = 2;
}

message GetUrlsRequest {
}

message GetUrlsResponse {
  repeated ShortUrl urls = 1;
}
/////////////////////////////////// "/{id}", c.GetLongURLHandler() - get the original URL  by the alias
message GetUrlRequest {
  string id = 1;
}

message GetUrlResponse {
  string url = 1;
}
///////////////////////////////////
message DeleteRequest {
  repeated string ids = 1; // ids - aliases to delete for a specific user
}

message DeleteResponse {
}
////////////////////////////////////
message BatchFullUrl {
  string correlation_id = 1;
  string original_url = 2;
}

message BatchShortUrl {
  string correlation_id = 1;
  string short_url = 2;
}
message BatchRequest {
  repeated BatchFullUrl urls = 1;
}

message BatchResponse {
  repeated BatchShortUrl result = 1;
}
///////////////////////////////////////

service Shortener {
  rpc PingDB(PingDBRequest) returns (PingDBResponse);
  rpc CreateShortURL(CreateShortURLRequest) returns (CreateShortURLResponse);
  rpc Batch(BatchRequest) returns (BatchResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc GetURL(GetUrlRequest) returns (GetUrlResponse);
  rpc GetURLs(GetUrlsRequest) returns (GetUrlsResponse);
  rpc InternalStats(StatRequest) returns (StatResponse);
}


/*protoc --go_out=. --go_opt=paths=source_relative \
--go-grpc_out=. --go-grpc_opt=paths=source_relative \
internal/protos/service.proto


grpcurl -plaintext -H 'username: habr' localhost:9001 client.Client.Test
 */